language: python
python:
- 3.7
- 3.8
dist: bionic
cache:
  pip: true
  apt: true
matrix:
  fast_finish: true
env:
  matrix:
  - UNIT_TEST=1
  - LINT_TEST=1

addons:
  apt:
    packages:
      - libjpeg-dev
      - libgnutls28-dev
      - libjpeg-progs
      - libimage-exiftool-perl
      - gifsicle
      - scons
      - python-all-dev
      - libboost-python-dev
      - libexiv2-dev
      - ffmpeg

install:
  - pip install coveralls
  - pip install --upgrade pip
  - pip install poetry
  - cd $TRAVIS_BUILD_DIR && make setup
  - pip install coveralls

script:
  - make ci-test

after_success:
  coveralls
