# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='remotecv',
    version='3.0.0',
    description='remotecv is an OpenCV worker for facial and feature recognition',
    python_requires='==3.*,>=3.7.0',
    author='Bernardo Heynemann',
    author_email='heynemann@gmail.com',
    license='MIT',
    entry_points={"console_scripts": ["remotecv = remotecv.worker:main"]},
    packages=[
        'remotecv', 'remotecv.detectors',
        'remotecv.detectors.complete_detector',
        'remotecv.detectors.face_detector',
        'remotecv.detectors.feature_detector',
        'remotecv.detectors.glasses_detector',
        'remotecv.detectors.profile_detector', 'remotecv.result_store'
    ],
    package_dir={"": "."},
    package_data={
        "remotecv.detectors.face_detector": ["*.xml"],
        "remotecv.detectors.glasses_detector": ["*.xml"],
        "remotecv.detectors.profile_detector": ["*.xml"]
    },
    install_requires=[
        'opencv-python-headless==4.*,>=4.2.0', 'pillow==7.*,>=7.0.0',
        'pyres==1.*,>=1.5.0'
    ],
    extras_require={
        "dev": [
            "black==19.*,>=19.10.0", "celery==4.*,>=4.4.1",
            "flake8==3.*,>=3.7.9", "preggy==1.*,>=1.4.4", "pylint==2.*,>=2.4.4",
            "pytest==5.*,>=5.3.5", "pytest-asyncio==0.*,>=0.10.0",
            "pytest-cov==2.*,>=2.8.1", "pytest-tldr==0.*,>=0.2.1",
            "pytest-xdist==1.*,>=1.31.0", "sentry-sdk==0.*,>=0.14.2"
        ]
    },
)
